### ISSUE TITLE
NDC Code Label/Descriptions are not consistent

### ISSUE THREAD

**Issue by JoshHull** [immregistries/codebase#3]
I'm not sure if the labels are Correct.  But I have noticed they're not consistent. 

I think the label/descriptions need to be reviewed and corrected. 

For example, NDC unit of Use: 
49281-0545-15
49281-0560-05

Those have the same CVX/MFR codes, but different Label/Description. Here's the full data: 

NDC Unit Of Use Code | Label | Description | CVX | MFR | Linked NDC Unit Of Sale Code
-- | -- | -- | -- | -- | --
49281-0545-15 | ACTHIB | Sanofi Pasteur Inc. - HAEMOPHILUS B CONJUGATE VACCINE (TETANUS TOXOID CONJUGATE) | 120 | PMC | 49281-0510-05
49281-0560-05 | DTAP-IPV | Sanofi Pasteur Inc. - DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS ADSORBED, INACTIVATED POLIOVIRUS | 120 | PMC | 49281-0510-05

Additionally, the labels are not always capitalized the same. 

Example is Afluria: 

NDC Unit Of Use Code | Label | Description | CVX | MFR | Linked NDC Unit Of Sale Code
-- | -- | -- | -- | -- | --
33332-0115-11 | AFLURIA | CSL Limited - INFLUENZA A VIRUS | 141 | CSL | 33332-0115-10
33332-0015-02 | AFLURIA | CSL Limited - INFLUENZA A VIRUS | 140 | CSL | 33332-0015-01
33332-0016-02 | Afluria | Seqirus - influenza vaccine | 140 | SEQ | 33332-0016-01
33332-0116-11 | Afluria | Seqirus - influenza vaccine | 141 | SEQ | 33332-0116-10
33332-0117-11 | Afluria | Seqirus - Influenza vaccine | 141 | SEQ | 33332-0117-10
33332-0017-02 | Afluria | Seqirus - Influenza vaccine | 140 | SEQ | 33332-0017-01
33332-0014-02 | AFLURIA | CSL Limited - INFLUENZA A VIRUS A/CALIFORNIA/7/2009 X-181 (H1N1) ANTIGEN (PROPIOLACTONE INACTIVATED), INFLUENZA A | 140 | CSL | 33332-0014-01
33332-0114-11 | AFLURIA | CSL Limited - INFLUENZA A VIRUS A/CALIFORNIA/7/2009 X-181 (H1N1) ANTIGEN (PROPIOLACTONE INACTIVATED), INFLUENZA A | 141 | CSL | 33332-0114-10
33332-0013-02 | AFLURIA | CSL Limited - INFLUENZA A VIRUS A/CALIFORNIA/7/2009 X-181 (H1N1) ANTIGEN (PROPIOLACTONE INACTIVATED), INFLUENZA A | 140 | CSL | 33332-0013-01
33332-0113-11 | AFLURIA | CSL Limited - INFLUENZA A VIRUS A/CALIFORNIA/7/2009 X-181 (H1N1) ANTIGEN (PROPIOLACTONE INACTIVATED), INFLUENZA A | 141 | CSL | 33332-0113-10
33332-0010-01 | AFLURIA | CSL Limited - INFLUENZA A VIRUS A/CALIFORNIA/7/2009 X-181 (H1N1) HEMAGGLUTININ ANTIGEN (PROPIOLACTONE INACTIVATED) | 140 | CSL | 33332-0010-01
33332-0110-10 | AFLURIA | CSL Limited - INFLUENZA A VIRUS A/CALIFORNIA/7/2009 X-181 (H1N1) HEMAGGLUTININ ANTIGEN (PROPIOLACTONE INACTIVATED) | 141 | CSL | 33332-0110-10

**Comment by sorech02** [comment]
@JoshHull  is this issue still valid?

The labels are generated from CDC source information, and we could direct the comments to them.
